LangString addOrReinstall ${LANG_HUNGARIAN} "Komponensek hozzáadása/újratelepítése"
LangString alreadyInstalled ${LANG_HUNGARIAN} "Már telepítve"
LangString alreadyInstalledLong ${LANG_HUNGARIAN} "A(z) ${PRODUCTNAME} ${VERSION} már telepítve van. Válaszd ki a végrehajtandó műveletet, és kattints a Tovább gombra."
LangString appRunning ${LANG_HUNGARIAN} "A(z) {{product_name}} fut! Kérlek, zárd be, majd próbáld újra."
LangString appRunningOkKill ${LANG_HUNGARIAN} "A(z) {{product_name}} fut!$\nKattints az OK gombra a bezáráshoz."
LangString chooseMaintenanceOption ${LANG_HUNGARIAN} "Válaszd ki a végrehajtandó karbantartási műveletet."
LangString choowHowToInstall ${LANG_HUNGARIAN} "Válaszd ki, hogyan szeretnéd telepíteni a(z) ${PRODUCTNAME} alkalmazást."
LangString createDesktop ${LANG_HUNGARIAN} "Asztali parancsikon létrehozása"
LangString dontUninstall ${LANG_HUNGARIAN} "Ne távolítsd el"
LangString dontUninstallDowngrade ${LANG_HUNGARIAN} "Ne távolítsd el (a visszalépés eltávolítás nélkül le van tiltva ennél a telepítőnél)"
LangString failedToKillApp ${LANG_HUNGARIAN} "Nem sikerült bezárni a(z) {{product_name}} alkalmazást. Kérlek, zárd be, majd próbáld újra."
LangString installingWebview2 ${LANG_HUNGARIAN} "WebView2 telepítése..."
LangString newerVersionInstalled ${LANG_HUNGARIAN} "A(z) ${PRODUCTNAME} egy újabb verziója már telepítve van! Nem ajánlott régebbi verziót telepíteni. Ha mégis ezt szeretnéd, először távolítsd el a jelenlegi verziót. Válaszd ki a végrehajtandó műveletet, és kattints a Tovább gombra."
LangString older ${LANG_HUNGARIAN} "régebbi"
LangString olderOrUnknownVersionInstalled ${LANG_HUNGARIAN} "A(z) ${PRODUCTNAME} egy $R4 verziója van telepítve a rendszeren. Ajánlott a jelenlegi verziót eltávolítani a telepítés előtt. Válaszd ki a végrehajtandó műveletet, és kattints a Tovább gombra."
LangString silentDowngrades ${LANG_HUNGARIAN} "A visszalépés le van tiltva ennél a telepítőnél, a csendes telepítő nem folytatható. Kérlek, használd a grafikus telepítőt.$\n"
LangString unableToUninstall ${LANG_HUNGARIAN} "Az eltávolítás nem sikerült!"
LangString uninstallApp ${LANG_HUNGARIAN} "${PRODUCTNAME} eltávolítása"
LangString uninstallBeforeInstalling ${LANG_HUNGARIAN} "Eltávolítás a telepítés előtt"
LangString unknown ${LANG_HUNGARIAN} "ismeretlen"
LangString webview2AbortError ${LANG_HUNGARIAN} "Nem sikerült a WebView2 telepítése! Az alkalmazás nem futtatható nélküle. Próbáld újraindítani a telepítőt."
LangString webview2DownloadError ${LANG_HUNGARIAN} "Hiba: A WebView2 letöltése sikertelen - $0"
LangString webview2DownloadSuccess ${LANG_HUNGARIAN} "A WebView2 telepítő sikeresen letöltve"
LangString webview2Downloading ${LANG_HUNGARIAN} "WebView2 telepítő letöltése..."
LangString webview2InstallError ${LANG_HUNGARIAN} "Hiba: A WebView2 telepítése sikertelen, kilépési kód: $1"
LangString webview2InstallSuccess ${LANG_HUNGARIAN} "A WebView2 sikeresen telepítve"
LangString deleteAppData ${LANG_HUNGARIAN} "Alkalmazásadatok törlése"
